name: 블로그 포스트 작성
description: 블로그 포스트를 작성할 때 사용하는 템플릿입니다.
body:
  - type: markdown
    attributes:
      value: |
        블로그 포스트를 작성할 때 사용하는 템플릿입니다. 아래의 내용을 작성해주세요.

  - type: textarea
    id: 주제
    attributes:
      label: title
      description: |
        포스팅할 주제를 간략하게 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: 목적
    attributes:
      label: purpose
      description: |
        포스팅을 작성하는 이유를 간략하게 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: 내용
    attributes:
      label: content
      description: |
        포스팅 내용을 간략하게 작성해주세요.
    validations:
      required: true